// Vehicle data structured as Make -> Base Model -> Trims
// When a trim is selected, it's used as the model name for pricing lookup

export type VehicleStructure = Record<string, Record<string, string[]>>;

export const VEHICLE_DATA: VehicleStructure = {
  "Acura": {
    "CL": ["CL"],
    "ILX": ["ILX"],
    "Integra": ["Integra", "Integra Type R", "Integra Type S"],
    "Legend": ["Legend"],
    "MDX": ["MDX", "MDX Type S"],
    "NSX": ["NSX", "NSX Type S"],
    "RDX": ["RDX", "RDX A-Spec"],
    "RL": ["RL"],
    "RLX": ["RLX"],
    "RSX": ["RSX", "RSX Type S"],
    "TL": ["TL", "TL Type S"],
    "TLX": ["TLX", "TLX Type S"],
    "TSX": ["TSX"],
    "ZDX": ["ZDX"],
  },
  "Alfa Romeo": {
    "4C": ["4C", "4C Spider"],
    "Giulia": ["Giulia", "Giulia Quadrifoglio"],
    "Stelvio": ["Stelvio", "Stelvio Quadrifoglio"],
    "Tonale": ["Tonale"],
  },
  "Aston Martin": {
    "DB9": ["DB9"],
    "DB11": ["DB11", "DB11 V12"],
    "DB12": ["DB12"],
    "DBS": ["DBS", "DBS Superleggera"],
    "Rapide": ["Rapide", "Rapide S"],
    "Vantage": ["Vantage", "Vantage AMR", "V8 Vantage", "V12 Vantage"],
    "Vanquish": ["Vanquish", "Vanquish S"],
  },
  "Audi": {
    "A3": ["A3", "A3 e-tron"],
    "A4": ["A4", "A4 allroad"],
    "A5": ["A5", "A5 Sportback"],
    "A6": ["A6", "A6 allroad"],
    "A7": ["A7"],
    "A8": ["A8", "A8 L"],
    "e-tron": ["e-tron", "e-tron S"],
    "e-tron GT": ["e-tron GT", "RS e-tron GT"],
    "Q3": ["Q3"],
    "Q4 e-tron": ["Q4 e-tron"],
    "Q5": ["Q5", "Q5 Sportback", "SQ5", "SQ5 Sportback"],
    "Q7": ["Q7", "SQ7"],
    "Q8": ["Q8", "Q8 e-tron", "SQ8", "RS Q8"],
    "R8": ["R8", "R8 V10", "R8 V10 Plus", "R8 V10 Performance"],
    "S3": ["S3"],
    "S4": ["S4"],
    "S5": ["S5", "S5 Sportback"],
    "S6": ["S6"],
    "S7": ["S7"],
    "S8": ["S8"],
    "RS 3": ["RS 3"],
    "RS 5": ["RS 5", "RS 5 Sportback"],
    "RS 6": ["RS 6 Avant"],
    "RS 7": ["RS 7"],
    "TT": ["TT", "TT S", "TT RS"],
  },
  "BMW": {
    "2 Series": ["228i", "230i", "M235i", "M240i"],
    "3 Series": ["318i", "320i", "323i", "325i", "328i", "328d", "330e", "330i", "M340i"],
    "4 Series": ["428i", "430i", "435i", "440i", "M440i"],
    "5 Series": ["528i", "530e", "530i", "535i", "540i", "M550i"],
    "6 Series": ["640i", "645Ci", "650i"],
    "7 Series": ["740i", "745e", "750i", "760i"],
    "8 Series": ["840i", "M850i"],
    "M2": ["M2", "M2 Competition"],
    "M3": ["M3", "M3 Competition"],
    "M4": ["M4", "M4 Competition", "M4 CS", "M4 GTS"],
    "M5": ["M5", "M5 Competition", "M5 CS"],
    "M6": ["M6", "M6 Gran Coupe"],
    "M8": ["M8", "M8 Competition", "M8 Gran Coupe"],
    "X1": ["X1"],
    "X2": ["X2"],
    "X3": ["X3", "X3 M40i", "X3 M", "X3 M Competition"],
    "X4": ["X4", "X4 M40i", "X4 M"],
    "X5": ["X5", "X5 M50i", "X5 M", "X5 M Competition"],
    "X6": ["X6", "X6 M50i", "X6 M", "X6 M Competition"],
    "X7": ["X7", "X7 M60i"],
    "XM": ["XM"],
    "Z3": ["Z3", "Z3 M Coupe", "Z3 M Roadster"],
    "Z4": ["Z4", "Z4 M40i"],
    "Z8": ["Z8"],
    "i3": ["i3"],
    "i4": ["i4", "i4 M50"],
    "i5": ["i5", "i5 M60"],
    "i7": ["i7", "i7 M70"],
    "i8": ["i8"],
    "iX": ["iX", "iX M60"],
    "1 Series": ["128i", "135i"],
  },
  "Bentley": {
    "Bentayga": ["Bentayga", "Bentayga Speed"],
    "Continental GT": ["Continental GT", "Continental GT Speed"],
    "Flying Spur": ["Flying Spur", "Flying Spur Speed", "Continental Flying Spur"],
    "Mulsanne": ["Mulsanne", "Mulsanne Speed"],
  },
  "Buick": {
    "Enclave": ["Enclave"],
    "Encore": ["Encore"],
    "Encore GX": ["Encore GX"],
    "Envision": ["Envision"],
    "Envista": ["Envista"],
    "Grand National": ["Grand National"],
    "LaCrosse": ["LaCrosse"],
    "Regal": ["Regal", "Regal GS"],
    "Riviera": ["Riviera"],
  },
  "Cadillac": {
    "ATS": ["ATS", "ATS-V"],
    "CT4": ["CT4", "CT4-V", "CT4-V Blackwing"],
    "CT5": ["CT5", "CT5-V", "CT5-V Blackwing"],
    "CT6": ["CT6", "CT6-V"],
    "CTS": ["CTS", "CTS-V"],
    "Escalade": ["Escalade", "Escalade ESV", "Escalade-V"],
    "Lyriq": ["Lyriq"],
    "STS": ["STS", "STS-V"],
    "XT4": ["XT4"],
    "XT5": ["XT5"],
    "XT6": ["XT6"],
    "XLR": ["XLR", "XLR-V"],
  },
  "Chevrolet": {
    "Blazer": ["Blazer", "Blazer RS", "Blazer EV", "Blazer EV SS"],
    "Bolt": ["Bolt EV", "Bolt EUV"],
    "Camaro": ["Camaro", "Camaro LT", "Camaro SS", "Camaro ZL1", "Camaro ZL1 1LE", "Camaro Z/28"],
    "Colorado": ["Colorado", "Colorado ZR2"],
    "Corvette": ["Corvette", "Corvette Stingray", "Corvette Z06", "Corvette Grand Sport", "Corvette ZR1", "Corvette E-Ray"],
    "Equinox": ["Equinox", "Equinox EV"],
    "Impala": ["Impala", "Impala SS"],
    "Malibu": ["Malibu"],
    "Silverado": ["Silverado 1500", "Silverado 1500 Trail Boss", "Silverado 1500 ZR2", "Silverado 2500HD"],
    "SS": ["SS"],
    "Suburban": ["Suburban"],
    "Tahoe": ["Tahoe"],
    "TrailBlazer": ["TrailBlazer"],
    "Traverse": ["Traverse"],
    "Cobalt": ["Cobalt", "Cobalt SS"],
    "El Camino": ["El Camino"],
    "Monte Carlo": ["Monte Carlo", "Monte Carlo SS"],
  },
  "Chrysler": {
    "200": ["200"],
    "300": ["300", "300 SRT8"],
    "Crossfire": ["Crossfire", "Crossfire SRT-6"],
    "Pacifica": ["Pacifica"],
    "PT Cruiser": ["PT Cruiser", "PT Cruiser GT"],
  },
  "Dodge": {
    "Challenger": ["Challenger", "Challenger R/T", "Challenger R/T Scat Pack", "Challenger SRT Hellcat", "Challenger SRT Hellcat Redeye", "Challenger SRT Demon", "Challenger SRT Demon 170", "Challenger SRT Super Stock"],
    "Charger": ["Charger", "Charger R/T", "Charger R/T Scat Pack", "Charger SRT Hellcat", "Charger SRT Hellcat Redeye", "Charger Daytona"],
    "Dart": ["Dart", "Dart GT"],
    "Durango": ["Durango", "Durango R/T", "Durango SRT", "Durango SRT Hellcat"],
    "Grand Caravan": ["Grand Caravan"],
    "Hornet": ["Hornet", "Hornet R/T"],
    "Magnum": ["Magnum", "Magnum SRT8"],
    "Neon": ["Neon", "Neon SRT-4"],
    "Viper": ["Viper", "Viper GTS", "Viper ACR", "Viper SRT10"],
  },
  "Ferrari": {
    "296": ["296 GTB", "296 GTS"],
    "348": ["348"],
    "360": ["360 Modena", "360 Spider"],
    "430": ["430 Scuderia"],
    "458": ["458 Italia", "458 Spider", "458 Speciale"],
    "488": ["488 GTB", "488 Spider", "488 Pista"],
    "550": ["550 Maranello"],
    "599": ["599 GTB", "599 GTO"],
    "812": ["812 Superfast", "812 GTS", "812 Competizione"],
    "California": ["California", "California T"],
    "F355": ["F355"],
    "F40": ["F40"],
    "F8": ["F8 Tributo", "F8 Spider"],
    "GTC4Lusso": ["GTC4Lusso"],
    "LaFerrari": ["LaFerrari"],
    "Portofino": ["Portofino", "Portofino M"],
    "Roma": ["Roma", "Roma Spider"],
    "SF90": ["SF90 Stradale", "SF90 Spider"],
    "Testarossa": ["Testarossa"],
  },
  "FIAT": {
    "124 Spider": ["124 Spider", "124 Spider Abarth"],
    "500": ["500", "500 Abarth", "500e", "500L", "500X"],
  },
  "Ford": {
    "Bronco": ["Bronco", "Bronco Raptor", "Bronco Badlands", "Bronco Wildtrak"],
    "Bronco Sport": ["Bronco Sport", "Bronco Sport Badlands"],
    "Edge": ["Edge", "Edge ST"],
    "Escape": ["Escape"],
    "Expedition": ["Expedition"],
    "Explorer": ["Explorer", "Explorer ST"],
    "F-150": ["F-150", "F-150 Raptor", "F-150 Raptor R", "F-150 Tremor", "F-150 Lightning"],
    "F-250": ["F-250"],
    "F-350": ["F-350"],
    "Fiesta": ["Fiesta", "Fiesta ST"],
    "Focus": ["Focus", "Focus ST", "Focus RS"],
    "Fusion": ["Fusion", "Fusion Sport"],
    "GT": ["GT"],
    "Maverick": ["Maverick"],
    "Mustang": ["Mustang", "Mustang GT", "Mustang EcoBoost", "Mustang Bullitt", "Mustang Mach 1", "Mustang Shelby GT350", "Mustang Shelby GT350R", "Mustang Shelby GT500", "Mustang Dark Horse"],
    "Mustang Mach-E": ["Mustang Mach-E", "Mustang Mach-E GT"],
    "Ranger": ["Ranger", "Ranger Raptor"],
    "Taurus": ["Taurus", "Taurus SHO"],
    "Thunderbird": ["Thunderbird"],
  },
  "Genesis": {
    "G70": ["G70"],
    "G80": ["G80", "G80 Sport"],
    "G90": ["G90"],
    "GV60": ["GV60"],
    "GV70": ["GV70", "GV70 Sport"],
    "GV80": ["GV80"],
  },
  "GMC": {
    "Acadia": ["Acadia", "Acadia AT4"],
    "Canyon": ["Canyon", "Canyon AT4X"],
    "Hummer EV": ["Hummer EV", "Hummer EV SUV"],
    "Sierra": ["Sierra 1500", "Sierra 1500 AT4", "Sierra 1500 AT4X", "Sierra 1500 Denali", "Sierra 2500HD"],
    "Terrain": ["Terrain"],
    "Yukon": ["Yukon", "Yukon AT4", "Yukon Denali", "Yukon XL"],
  },
  "Honda": {
    "Accord": ["Accord", "Accord Sport", "Accord Touring", "Accord Hybrid"],
    "Civic": ["Civic", "Civic Sport", "Civic Si", "Civic Type R"],
    "CR-V": ["CR-V", "CR-V Hybrid"],
    "CR-Z": ["CR-Z"],
    "Element": ["Element"],
    "Fit": ["Fit", "Fit Sport"],
    "HR-V": ["HR-V"],
    "Insight": ["Insight"],
    "Odyssey": ["Odyssey"],
    "Passport": ["Passport", "Passport TrailSport"],
    "Pilot": ["Pilot", "Pilot TrailSport"],
    "Prelude": ["Prelude"],
    "Prologue": ["Prologue"],
    "Ridgeline": ["Ridgeline"],
    "S2000": ["S2000", "S2000 CR"],
    "del Sol": ["del Sol"],
  },
  "Hyundai": {
    "Elantra": ["Elantra", "Elantra N", "Elantra N Line"],
    "Genesis Coupe": ["Genesis Coupe"],
    "Ioniq 5": ["Ioniq 5", "Ioniq 5 N"],
    "Ioniq 6": ["Ioniq 6"],
    "Kona": ["Kona", "Kona N", "Kona Electric"],
    "Palisade": ["Palisade"],
    "Santa Cruz": ["Santa Cruz"],
    "Santa Fe": ["Santa Fe"],
    "Sonata": ["Sonata", "Sonata N Line"],
    "Tiburon": ["Tiburon"],
    "Tucson": ["Tucson", "Tucson N Line"],
    "Veloster": ["Veloster", "Veloster N", "Veloster Turbo"],
  },
  "INFINITI": {
    "G35": ["G35", "G35 Coupe"],
    "G37": ["G37", "G37 Coupe", "G37 IPL"],
    "Q50": ["Q50", "Q50 Red Sport 400"],
    "Q60": ["Q60", "Q60 Red Sport 400"],
    "QX50": ["QX50"],
    "QX55": ["QX55"],
    "QX60": ["QX60"],
    "QX80": ["QX80"],
    "FX35": ["FX35"],
    "FX45": ["FX45"],
  },
  "Jaguar": {
    "E-Pace": ["E-Pace"],
    "F-Pace": ["F-Pace", "F-Pace SVR"],
    "F-Type": ["F-Type", "F-Type R", "F-Type SVR"],
    "I-Pace": ["I-Pace"],
    "XE": ["XE", "XE SV Project 8"],
    "XF": ["XF", "XFR", "XFR-S"],
    "XJ": ["XJ", "XJR", "XJR575"],
    "XK": ["XK", "XKR", "XKR-S"],
  },
  "Jeep": {
    "Cherokee": ["Cherokee", "Cherokee Trailhawk"],
    "Compass": ["Compass", "Compass Trailhawk"],
    "Gladiator": ["Gladiator", "Gladiator Rubicon", "Gladiator Mojave"],
    "Grand Cherokee": ["Grand Cherokee", "Grand Cherokee Trailhawk", "Grand Cherokee SRT", "Grand Cherokee Trackhawk", "Grand Cherokee L"],
    "Grand Wagoneer": ["Grand Wagoneer"],
    "Renegade": ["Renegade", "Renegade Trailhawk"],
    "Wagoneer": ["Wagoneer"],
    "Wrangler": ["Wrangler", "Wrangler Rubicon", "Wrangler Sahara", "Wrangler Unlimited", "Wrangler Rubicon 392"],
  },
  "Kia": {
    "Carnival": ["Carnival"],
    "EV6": ["EV6", "EV6 GT"],
    "EV9": ["EV9", "EV9 GT"],
    "Forte": ["Forte", "Forte GT"],
    "K5": ["K5", "K5 GT"],
    "Niro": ["Niro", "Niro EV"],
    "Optima": ["Optima", "Optima SX"],
    "Seltos": ["Seltos"],
    "Soul": ["Soul"],
    "Sorento": ["Sorento", "Sorento SX"],
    "Sportage": ["Sportage", "Sportage X-Pro"],
    "Stinger": ["Stinger", "Stinger GT"],
    "Telluride": ["Telluride", "Telluride SX"],
  },
  "Lamborghini": {
    "Aventador": ["Aventador", "Aventador S", "Aventador SVJ"],
    "Countach": ["Countach", "Countach LPI 800-4"],
    "Diablo": ["Diablo"],
    "Gallardo": ["Gallardo", "Gallardo Superleggera"],
    "Huracan": ["Huracan", "Huracan Performante", "Huracan STO", "Huracan Tecnica", "Huracan Sterrato"],
    "Murcielago": ["Murcielago"],
    "Revuelto": ["Revuelto"],
    "Urus": ["Urus", "Urus S", "Urus Performante"],
  },
  "Land Rover": {
    "Defender": ["Defender", "Defender 90", "Defender 110", "Defender 130", "Defender V8"],
    "Discovery": ["Discovery"],
    "Discovery Sport": ["Discovery Sport"],
    "Range Rover": ["Range Rover", "Range Rover SV"],
    "Range Rover Evoque": ["Range Rover Evoque"],
    "Range Rover Sport": ["Range Rover Sport", "Range Rover Sport SVR"],
    "Range Rover Velar": ["Range Rover Velar"],
  },
  "Lexus": {
    "ES": ["ES 300h", "ES 350", "ES 350 F Sport"],
    "GS": ["GS 350", "GS 350 F Sport", "GS 450h", "GS F"],
    "GX": ["GX 460", "GX 470", "GX 550"],
    "IS": ["IS 250", "IS 300", "IS 350", "IS 350 F Sport", "IS 500", "IS 500 F Sport Performance", "IS F"],
    "LC": ["LC 500", "LC 500 Convertible", "LC 500h"],
    "LFA": ["LFA"],
    "LS": ["LS 400", "LS 430", "LS 460", "LS 460 F Sport", "LS 500", "LS 500h", "LS 500 F Sport"],
    "LX": ["LX 470", "LX 570", "LX 600", "LX 600 F Sport"],
    "NX": ["NX 250", "NX 350", "NX 350h", "NX 350 F Sport", "NX 450h+"],
    "RC": ["RC 300", "RC 350", "RC 350 F Sport", "RC F", "RC F Track Edition"],
    "RX": ["RX 330", "RX 350", "RX 350 F Sport", "RX 350h", "RX 450h", "RX 450h+", "RX 500h"],
    "RZ": ["RZ 450e"],
    "SC": ["SC 300", "SC 400", "SC 430"],
    "TX": ["TX 350", "TX 500h"],
    "UX": ["UX 200", "UX 250h"],
  },
  "Lincoln": {
    "Aviator": ["Aviator", "Aviator Grand Touring"],
    "Continental": ["Continental"],
    "Corsair": ["Corsair", "Corsair Grand Touring"],
    "Navigator": ["Navigator", "Navigator L"],
    "MKZ": ["MKZ"],
    "Town Car": ["Town Car"],
  },
  "Lotus": {
    "Elise": ["Elise"],
    "Emira": ["Emira"],
    "Esprit": ["Esprit"],
    "Evora": ["Evora", "Evora GT"],
    "Exige": ["Exige", "Exige S"],
  },
  "Maserati": {
    "Ghibli": ["Ghibli", "Ghibli Trofeo"],
    "GranTurismo": ["GranTurismo", "GranTurismo Trofeo"],
    "Grecale": ["Grecale", "Grecale Trofeo"],
    "Levante": ["Levante", "Levante Trofeo"],
    "MC20": ["MC20", "MC20 Cielo"],
    "Quattroporte": ["Quattroporte", "Quattroporte Trofeo"],
  },
  "Mazda": {
    "3": ["Mazda3", "Mazda3 Turbo", "Mazdaspeed3"],
    "6": ["Mazda6", "Mazda6 Turbo", "Mazdaspeed6"],
    "CX-3": ["CX-3"],
    "CX-30": ["CX-30", "CX-30 Turbo"],
    "CX-5": ["CX-5", "CX-5 Turbo"],
    "CX-50": ["CX-50", "CX-50 Turbo"],
    "CX-9": ["CX-9"],
    "CX-70": ["CX-70"],
    "CX-90": ["CX-90", "CX-90 PHEV"],
    "MX-5 Miata": ["MX-5 Miata", "MX-5 Miata RF"],
    "RX-7": ["RX-7", "RX-7 Turbo"],
    "RX-8": ["RX-8"],
  },
  "McLaren": {
    "540C": ["540C"],
    "570S": ["570S", "570S Spider", "570GT"],
    "600LT": ["600LT", "600LT Spider"],
    "650S": ["650S", "650S Spider"],
    "675LT": ["675LT", "675LT Spider"],
    "720S": ["720S", "720S Spider"],
    "750S": ["750S", "750S Spider"],
    "765LT": ["765LT", "765LT Spider"],
    "Artura": ["Artura"],
    "GT": ["GT"],
    "MP4-12C": ["MP4-12C"],
    "P1": ["P1"],
    "Senna": ["Senna"],
  },
  "Mercedes-Benz": {
    "A-Class": ["A 220", "A 35 AMG"],
    "C-Class": ["C 300", "C 43 AMG", "C 55 AMG", "C 63 AMG", "C 63 S AMG"],
    "CLA-Class": ["CLA 250", "CLA 35 AMG", "CLA 45 AMG"],
    "CLK-Class": ["CLK 320", "CLK 350", "CLK 430", "CLK 500", "CLK 55 AMG", "CLK 63 AMG"],
    "CLS-Class": ["CLS 450", "CLS 500", "CLS 53 AMG", "CLS 55 AMG", "CLS 550", "CLS 63 AMG"],
    "E-Class": ["E 300", "E 350", "E 400", "E 43 AMG", "E 450", "E 500", "E 53 AMG", "E 55 AMG", "E 550", "E 63 AMG", "E 63 S AMG"],
    "EQB": ["EQB 300", "EQB 350"],
    "EQE": ["EQE 350+", "EQE 500"],
    "EQS": ["EQS 450+", "EQS 580"],
    "G-Class": ["G 550", "G 55 AMG", "G 63 AMG", "G 65 AMG"],
    "GLA-Class": ["GLA 250", "GLA 35 AMG", "GLA 45 AMG"],
    "GLB-Class": ["GLB 250", "GLB 35 AMG"],
    "GLC-Class": ["GLC 300", "GLC 43 AMG", "GLC 63 AMG", "GLC 63 S AMG"],
    "GLE-Class": ["GLE 350", "GLE 450", "GLE 53 AMG", "GLE 580", "GLE 63 AMG", "GLE 63 S AMG"],
    "GLK-Class": ["GLK 250", "GLK 350"],
    "GLS-Class": ["GLS 450", "GLS 580", "GLS 63 AMG"],
    "AMG GT": ["AMG GT", "AMG GT 43", "AMG GT 53", "AMG GT 63", "AMG GT 63 S", "AMG GT C", "AMG GT R", "AMG GT S"],
    "CL-Class": ["CL 550", "CL 55 AMG", "CL 63 AMG", "CL 65 AMG"],
    "Maybach": ["Maybach S 580", "Maybach S 680", "Maybach GLS 600"],
    "ML-Class": ["ML 350", "ML 500", "ML 55 AMG", "ML 550", "ML 63 AMG"],
    "R-Class": ["R 350", "R 500", "R 63 AMG"],
    "S-Class": ["S 450", "S 500", "S 550", "S 560", "S 580", "S 600", "S 55 AMG", "S 63 AMG", "S 65 AMG"],
    "SL-Class": ["SL 400", "SL 43 AMG", "SL 450", "SL 500", "SL 55 AMG", "SL 550", "SL 63 AMG", "SL 65 AMG"],
    "SLC-Class": ["SLC 300", "SLC 43 AMG"],
    "SLK-Class": ["SLK 230", "SLK 250", "SLK 300", "SLK 350", "SLK 55 AMG"],
    "SLR McLaren": ["SLR McLaren"],
    "SLS": ["SLS AMG"],
  },
  "MINI": {
    "Cooper": ["Cooper", "Cooper S"],
    "Clubman": ["Clubman", "Clubman S", "Clubman JCW"],
    "Countryman": ["Countryman", "Countryman S", "Countryman JCW"],
    "John Cooper Works": ["John Cooper Works", "John Cooper Works GP"],
  },
  "Mitsubishi": {
    "3000GT": ["3000GT", "3000GT VR-4"],
    "Eclipse": ["Eclipse", "Eclipse GT"],
    "Eclipse Cross": ["Eclipse Cross"],
    "Lancer": ["Lancer", "Lancer Evolution", "Lancer Ralliart"],
    "Mirage": ["Mirage"],
    "Outlander": ["Outlander", "Outlander PHEV", "Outlander Sport"],
  },
  "Nissan": {
    "240SX": ["240SX"],
    "300ZX": ["300ZX", "300ZX Turbo"],
    "350Z": ["350Z", "350Z Nismo"],
    "370Z": ["370Z", "370Z Nismo"],
    "Altima": ["Altima", "Altima SR"],
    "Armada": ["Armada"],
    "Frontier": ["Frontier", "Frontier PRO-4X"],
    "GT-R": ["GT-R", "GT-R Nismo", "GT-R Track Edition", "GT-R Premium"],
    "Juke": ["Juke", "Juke Nismo"],
    "Kicks": ["Kicks"],
    "Leaf": ["Leaf", "Leaf Plus"],
    "Maxima": ["Maxima", "Maxima SR"],
    "Murano": ["Murano"],
    "Pathfinder": ["Pathfinder"],
    "Rogue": ["Rogue", "Rogue Sport"],
    "Sentra": ["Sentra", "Sentra SE-R Spec V"],
    "Titan": ["Titan", "Titan PRO-4X"],
    "Z": ["Z", "Z Nismo", "Z Performance"],
  },
  "Pontiac": {
    "Fiero": ["Fiero", "Fiero GT"],
    "Firebird": ["Firebird", "Firebird Trans Am", "Firebird Formula"],
    "G6": ["G6", "G6 GTP"],
    "G8": ["G8", "G8 GT", "G8 GXP"],
    "Grand Am": ["Grand Am"],
    "Grand Prix": ["Grand Prix", "Grand Prix GTP"],
    "GTO": ["GTO"],
    "Solstice": ["Solstice", "Solstice GXP"],
  },
  "Porsche": {
    "718 Boxster": ["718 Boxster", "718 Boxster S", "718 Boxster GTS", "718 Boxster T", "718 Boxster Spyder"],
    "718 Cayman": ["718 Cayman", "718 Cayman S", "718 Cayman GTS", "718 Cayman T", "718 Cayman GT4", "718 Cayman GT4 RS"],
    "911": ["911 Carrera", "911 Carrera S", "911 Carrera T", "911 Carrera GTS", "911 Carrera 4", "911 Carrera 4S", "911 Targa 4", "911 Targa 4S", "911 Turbo", "911 Turbo S", "911 GT3", "911 GT3 RS", "911 GT3 Touring", "911 GT2 RS", "911 Sport Classic", "911 Dakar", "911 S/T"],
    "918 Spyder": ["918 Spyder"],
    "Boxster": ["Boxster", "Boxster S", "Boxster GTS", "Boxster Spyder"],
    "Carrera GT": ["Carrera GT"],
    "Cayenne": ["Cayenne", "Cayenne S", "Cayenne E-Hybrid", "Cayenne GTS", "Cayenne Turbo", "Cayenne Turbo S", "Cayenne Turbo GT", "Cayenne Coupe", "Cayenne Coupe Turbo GT"],
    "Cayman": ["Cayman", "Cayman S", "Cayman GTS", "Cayman R"],
    "Macan": ["Macan", "Macan S", "Macan GTS", "Macan T", "Macan Turbo"],
    "Panamera": ["Panamera", "Panamera 4", "Panamera 4S", "Panamera GTS", "Panamera Turbo", "Panamera Turbo S"],
    "Taycan": ["Taycan", "Taycan 4S", "Taycan GTS", "Taycan Turbo", "Taycan Turbo S", "Taycan Cross Turismo"],
    "924": ["924"],
    "928": ["928"],
    "944": ["944"],
    "968": ["968"],
  },
  "RAM": {
    "1500": ["1500", "1500 Classic", "1500 TRX", "1500 Rebel", "1500 Laramie"],
    "2500": ["2500", "2500 Power Wagon"],
    "3500": ["3500"],
  },
  "Rivian": {
    "R1S": ["R1S"],
    "R1T": ["R1T"],
    "R2": ["R2"],
  },
  "Rolls-Royce": {
    "Cullinan": ["Cullinan", "Cullinan Black Badge"],
    "Dawn": ["Dawn", "Dawn Black Badge"],
    "Ghost": ["Ghost", "Ghost Black Badge", "Ghost Extended"],
    "Phantom": ["Phantom", "Phantom Extended"],
    "Spectre": ["Spectre"],
    "Wraith": ["Wraith", "Wraith Black Badge"],
  },
  "Saab": {
    "9-3": ["9-3", "9-3 Aero"],
    "9-5": ["9-5", "9-5 Aero"],
    "900": ["900", "900 Turbo"],
  },
  "Saturn": {
    "Ion": ["Ion", "Ion Red Line"],
    "Sky": ["Sky", "Sky Red Line"],
    "Vue": ["Vue"],
  },
  "Scion": {
    "FR-S": ["FR-S"],
    "tC": ["tC"],
    "xB": ["xB"],
  },
  "Subaru": {
    "Ascent": ["Ascent"],
    "BRZ": ["BRZ", "BRZ tS"],
    "Crosstrek": ["Crosstrek", "Crosstrek Wilderness"],
    "Forester": ["Forester", "Forester Sport", "Forester Wilderness"],
    "Impreza": ["Impreza"],
    "Legacy": ["Legacy", "Legacy GT"],
    "Outback": ["Outback", "Outback Wilderness", "Outback XT"],
    "Solterra": ["Solterra"],
    "WRX": ["WRX", "WRX TR"],
    "WRX STI": ["WRX STI", "WRX STI S209", "WRX STI Type RA"],
    "SVX": ["SVX"],
  },
  "Suzuki": {
    "Grand Vitara": ["Grand Vitara"],
    "Kizashi": ["Kizashi", "Kizashi Sport"],
    "SX4": ["SX4"],
    "Swift": ["Swift", "Swift Sport"],
  },
  "Tesla": {
    "Cybertruck": ["Cybertruck"],
    "Model 3": ["Model 3", "Model 3 Performance", "Model 3 Long Range"],
    "Model S": ["Model S", "Model S Plaid", "Model S Long Range"],
    "Model X": ["Model X", "Model X Plaid", "Model X Long Range"],
    "Model Y": ["Model Y", "Model Y Performance", "Model Y Long Range"],
    "Roadster": ["Roadster"],
  },
  "Toyota": {
    "4Runner": ["4Runner", "4Runner TRD Off-Road", "4Runner TRD Pro"],
    "86": ["86"],
    "Avalon": ["Avalon", "Avalon TRD"],
    "bZ4X": ["bZ4X"],
    "Camry": ["Camry", "Camry SE", "Camry XSE", "Camry TRD"],
    "Celica": ["Celica", "Celica GT-S"],
    "Corolla": ["Corolla", "Corolla SE", "Corolla Hatchback", "Corolla Cross", "Corolla Cross Hybrid"],
    "Crown": ["Crown"],
    "FJ Cruiser": ["FJ Cruiser"],
    "GR Corolla": ["GR Corolla", "GR Corolla Morizo"],
    "GR86": ["GR86"],
    "GR Supra": ["GR Supra", "GR Supra 3.0", "GR Supra 3.0 Premium"],
    "Highlander": ["Highlander", "Highlander Hybrid"],
    "Land Cruiser": ["Land Cruiser"],
    "MR2": ["MR2", "MR2 Spyder"],
    "Prius": ["Prius", "Prius Prime"],
    "RAV4": ["RAV4", "RAV4 Prime", "RAV4 TRD Off-Road"],
    "Sequoia": ["Sequoia", "Sequoia TRD Pro"],
    "Sienna": ["Sienna"],
    "Supra": ["Supra", "Supra Turbo"],
    "Tacoma": ["Tacoma", "Tacoma TRD Sport", "Tacoma TRD Off-Road", "Tacoma TRD Pro"],
    "Tundra": ["Tundra", "Tundra TRD Pro"],
    "Venza": ["Venza"],
    "Yaris": ["Yaris", "Yaris GR"],
  },
  "Volkswagen": {
    "Arteon": ["Arteon", "Arteon R-Line"],
    "Atlas": ["Atlas", "Atlas Cross Sport"],
    "Beetle": ["Beetle", "Beetle Turbo"],
    "CC": ["CC", "CC R-Line"],
    "Corrado": ["Corrado", "Corrado VR6"],
    "Golf": ["Golf", "Golf GTI", "Golf R", "Golf R32"],
    "ID.4": ["ID.4"],
    "ID.Buzz": ["ID.Buzz"],
    "Jetta": ["Jetta", "Jetta GLI"],
    "Passat": ["Passat"],
    "R32": ["R32"],
    "Taos": ["Taos"],
    "Tiguan": ["Tiguan", "Tiguan R-Line"],
    "Touareg": ["Touareg"],
  },
  "Volvo": {
    "C30": ["C30", "C30 R-Design"],
    "C40": ["C40 Recharge"],
    "C70": ["C70"],
    "EX30": ["EX30"],
    "EX90": ["EX90"],
    "S60": ["S60", "S60 Polestar", "S60 R"],
    "S90": ["S90"],
    "V60": ["V60", "V60 Polestar", "V60 Cross Country"],
    "V70": ["V70", "V70 R"],
    "V90": ["V90", "V90 Cross Country"],
    "XC40": ["XC40", "XC40 Recharge"],
    "XC60": ["XC60", "XC60 Polestar"],
    "XC70": ["XC70"],
    "XC90": ["XC90"],
    "240": ["240", "240 Turbo"],
    "850": ["850", "850 T-5R", "850 R"],
  },
};

export function getAllMakes(): string[] {
  return Object.keys(VEHICLE_DATA).sort();
}

export function getModelsForMake(make: string): string[] {
  const makeData = VEHICLE_DATA[make];
  if (!makeData) return [];
  return Object.keys(makeData).sort();
}

export function getTrimsForModel(make: string, model: string): string[] {
  const makeData = VEHICLE_DATA[make];
  if (!makeData) return [];
  return makeData[model] || [];
}

export function getYearRange(): number[] {
  const currentYear = new Date().getFullYear();
  const years: number[] = [];
  for (let y = currentYear + 1; y >= 1990; y--) {
    years.push(y);
  }
  return years;
}
